### ISSUE TITLE
First screenshot duplicated

### ISSUE THREAD

**Issue by hadess** [flathub/net.sourceforge.Teo#1]
On https://flathub.org/apps/details/net.sourceforge.Teo, only the first screenshot appears 4 times, and loading anything past the first one shows a spinner.

Might be related to:
https://github.com/hughsie/appstream-glib/issues/244

Might be worked-around by:
https://github.com/flathub/net.sourceforge.Teo/commit/bf96bd653cccc4b4bc825bad7ef7114751c3f7a7#diff-955ae17f80b84ff3cc118ab7c247f4d6R7211

**Comment by ramcq** [comment]
@jgarciao Could this be a https://github.com/jgarciao/appstream-appdata-java/ issue?

**Comment by jgarciao** [comment]
These are the screenshots that are defined in the appstream file (/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml.gz) which is the file where the webapp backend gets the information:

```
    <screenshots>
      <screenshot type="default">
        <image type="source">https://a.fsdn.com/con/app/proj/teoemulator/screenshots/teo.png/max/max/1</image>
        <image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/624x351/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/112x63/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/224x126/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/752x423/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
      </screenshot>
      <screenshot>
        <image type="source">https://a.fsdn.com/con/app/proj/teoemulator/screenshots/teos2.png/max/max/1</image>
        <image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/624x351/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/112x63/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/224x126/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/752x423/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
      </screenshot>
      <screenshot>
        <image type="source">https://a.fsdn.com/con/app/proj/teoemulator/screenshots/teos3.png/max/max/1</image>
        <image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/624x351/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/112x63/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/224x126/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/752x423/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
      </screenshot>
      <screenshot>
        <image type="source">https://a.fsdn.com/con/app/proj/teoemulator/screenshots/teos4.png/max/max/1</image>
        <image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/624x351/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/112x63/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/224x126/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
        <image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/net.sourceforge.Teo-stable/752x423/net.sourceforge.Teo-a2c158b1453e2f5c7f11e48d1b3ebc82.png</image>
      </screenshot>
    </screenshots>

```
As you can see there is not localization information.

I see also that all the screenshots where image type is thumbnail are pointing to the same images. I think the problem is in the script that generates the screenshots for different resolutions.

 I've seen problems with this script before (for example [here](https://github.com/flathub/de.wolfvollprecht.UberWriter/issues/2)) and the problem was related to the resolution of the source screenshots. The ones provided by this app are 354x234. Maybe they are too small ...

**Comment by jgarciao** [comment]
This app is new and the screenshots look fine (source screenshot is 960px × 674px) : https://flathub.org/apps/details/org.eu.encom.matrique

This are also recent but have the same problem:
- (source screenshot is 480x259) https://flathub.org/apps/details/org.kde.kdiamond
- (source screenshot is 480x259) https://flathub.org/apps/details/org.kde.killbots

If we confirm that the problem is in the resolution we should write screenshot requirements in the [App Requirements Page](https://github.com/flathub/flathub/wiki/App-Requirements)

**Comment by hadess** [comment]
> If we confirm that the problem is in the resolution we should write screenshot requirements in the App Requirements Page

I'd rather we fixed the buggy app that generates those.

**Comment by jgarciao** [comment]
I think they are generated with `appstream-util mirror-screenshots ` as described in the [related issue](https://github.com/flathub/de.wolfvollprecht.UberWriter/issues/2#issuecomment-393197277)

**Comment by nedrichards** [comment]
We can certainly repeat the same level of information from [the spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) - and that would be helpful:

>  Ideally, all screenshots should have a 16:9 aspect ratio, and should have a width that is no smaller than 620 pixels. They should also be in be in PNG or JPEG format. PNG is the preferred format; JPEG should only be used when screenshots include large photographs or other images where a lossy format like JPEG may compress better.

**Comment by hadess** [comment]
`appstream-util validate` already warns about the screenshot sizes. Except that this isn't the problem at hand, the problem is a buggy host side script, which I'd rather we fixed before I invest time in better screenshots.

**Comment by hadess** [comment]
This is fixed now that I've updated the screenshots, but the wrong screenshot is now selected as the default (should be the menu).

**Comment by jgarciao** [comment]
I've investigated about the screenshot order and the issue might be in also in the screenshot generator script. More info here https://github.com/flathub/linux-store-frontend/issues/80
