### ISSUE TITLE
Add missing metadata to website

### ISSUE THREAD

**Issue by hadess** [flathub/net.sourceforge.Teo#2]
The metadata at:
https://flathub.org/apps/details/net.sourceforge.Teo
is missing Developer, Version and Updated.

**Comment by jgarciao** [comment]
This info should be informed in the appstream file for the app

For example for Krita:
```    
<developer_name>Krita Foundation</developer_name>
<developer_name xml:lang="ca">Fundació Krita</developer_name>
    
<releases>
    <release version="4.1.1.100" timestamp="1531872000"/>
</releases>
```
